---
title: "ch4_readcountsummary"
author: "allyson_demerlis"
date: "2023-08-20"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
sample_metadata <- read_csv("../input_files/sample_metadata.csv")
```

```{r}
sample_metadata %>% 
  select(Location, Genotype, `Tube No.`, `M Seqs (Raw Reads)`, `M Seqs (post-polyA trimming)`, `% Aligned`, `M Aligned`) %>% 
  mutate(percent_alignment = as.numeric(gsub("%","",`% Aligned`))) %>% 
  group_by(Location) %>% 
  drop_na() %>% 
  summarise(count = n(),
            total_raw_reads = sum(`M Seqs (Raw Reads)`), 
            total_trimmed_reads = sum(`M Seqs (post-polyA trimming)`), 
            average_rawreads_persample = mean(`M Seqs (Raw Reads)`), stdev_rawreads_persample = sd(`M Seqs (Raw Reads)`), 
            average_trimmedreads_persample = mean(`M Seqs (post-polyA trimming)`),
            stdev_trimmedreads_persample = sd(`M Seqs (post-polyA trimming)`),
            average_alignment_rate = mean(percent_alignment),
            stdev_alignmentrate = sd(percent_alignment))
  
  
```

