---
title: "Tidying Environmental Data"
author: "allyson_demerlis"
date: "2025-05-07"
output: html_document
---
# load libraries
```{r}
library(tidyverse)
library(readxl)
```

# import and tidy CCC temp logger (tilt meter)
```{r}
cures_frame_tilt_temp <- read_excel("raw_data/Oct2020_Jan2022_1901102_urban-2020-10_(0)_Temperature.xlsx", sheet = "1901102_urban-2020-10_(0)_Tempe")
#logged every 15 min

#edit cures frame time
cures_frame_tilt_temp$Datetime <- as.POSIXct(cures_frame_tilt_temp$Datetime, tz="UTC")
cures_frame_tilt_temp$Datetime_EST <- with_tz(cures_frame_tilt_temp$Datetime, "America/New_York")

# Filter the data to select time points at 2-hour intervals
cures_frame_tilt_temp <- cures_frame_tilt_temp %>%
  filter(minute(Datetime_EST) == 0 & (hour(Datetime_EST) %% 2 == 0))

#add cures frame site
cures_frame_tilt_temp %>% 
  mutate(site = "CCC") %>% 
  dplyr::select(!Date:Datetime) %>% 
  dplyr::rename(Temperature = `Temperature (C)`) -> cures_frame_tilt_temp

max(cures_frame_tilt_temp$Datetime_EST) #"2022-02-01 12:00:00 EST"
min(cures_frame_tilt_temp$Datetime_EST) #"2020-10-12 20:00:00 EDT"
```

plot all data to visualize
```{r}
ggplot(cures_frame_tilt_temp, aes(x=Datetime_EST, y=Temperature)) +
  geom_point()
```

```{r}
cures_frame_tilt_temp %>% 
  filter(as.Date(Datetime_EST) > "2021-06-01") -> CCC_temp_2021_06_01
```


```{r}
ggplot(CCC_temp_2021_06_01, aes(x=Datetime_EST, y=Temperature, color = site)) +
  geom_point(alpha = 0.7) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

calculate daily thermal variability during entire dataset
```{r}
CCC_temp_2021_06_01 %>% 
  group_by(as.Date(Datetime_EST)) %>% 
  summarise(mean_daily_temp = mean(Temperature), sd_daily_temp = sd(Temperature), daily_range = (max(Temperature)-min(Temperature))) %>% 
  ggplot(., aes(x=`as.Date(Datetime_EST)`, y=mean_daily_temp)) +
  geom_line() +
  theme_bw() 

CCC_temp_2021_06_01 %>% 
  group_by(as.Date(Datetime_EST)) %>% 
  summarise(mean_daily_temp = mean(Temperature), sd_daily_temp = sd(Temperature), daily_range = (max(Temperature)-min(Temperature))) %>% 
  ggplot(., aes(x=`as.Date(Datetime_EST)`, y=daily_range)) +
  geom_line() +
  theme_bw() 
```

# import and tidy KB Nursery HOBO logger
```{r}
#HOBO logs every two hours
convertFtoC <- function(F) {
  C <- (F - 32) * 5/9
  return(C)
}

KB_05282021 <- read_csv("raw_data/KBNursery_2021_05_28.csv", skip = 1)
KB_05282021 %>% 
  mutate(Datetime_EST=with_tz(mdy_hms(`Date Time, GMT-04:00`, tz = "Etc/GMT+4"), tzone = "Etc/GMT+4")) %>% 
  mutate(Datetime_EST=with_tz(Datetime_EST, tzone = "America/New_York")) %>% 
  dplyr::rename(Temperature = `Temp, °C (LGR S/N: 21085862, SEN S/N: 21085862)`) %>% 
  dplyr::select(Temperature, Datetime_EST) %>% 
  mutate(Light = NA) -> KB_05282021

KB_08112021 <- read_csv("raw_data/KBNursery_2021_08_11.csv", skip = 1)
KB_08112021 %>% 
  mutate(Datetime_EST=with_tz(mdy_hm(`Date Time, GMT-04:00`, tz = "Etc/GMT+4"), tzone = "Etc/GMT+4")) %>% 
  mutate(Datetime_EST=with_tz(Datetime_EST, tzone = "America/New_York")) %>% 
  dplyr::rename(Temperature = `Temp, °C (LGR S/N: 20831178, SEN S/N: 20831178)`) %>% 
  dplyr::rename(Light = `Intensity, lum/ft² (LGR S/N: 20831178, SEN S/N: 20831178)`) %>% 
  dplyr::select(Temperature, Light, Datetime_EST) -> KB_08112021

KB_120821 <- read_csv("raw_data/KBNursery_2021_12_08.csv", skip = 1)
KB_120821%>% 
  mutate(Datetime_EST=with_tz(mdy_hm(`Date Time, GMT-05:00`, tz = "Etc/GMT+5"), tzone = "Etc/GMT+5")) %>% 
  mutate(Datetime_EST=with_tz(Datetime_EST, tzone = "America/New_York")) %>% 
  dplyr::rename(Temperature = `Temp, °C (LGR S/N: 21236769, SEN S/N: 21236769)`) %>% 
  dplyr::rename(Light = `Intensity, lum/ft² (LGR S/N: 21236769, SEN S/N: 21236769)`) %>% 
  dplyr::select(Temperature, Light, Datetime_EST) -> KB_120821

rbind(KB_05282021, KB_08112021, KB_120821) -> all_KB_data

all_KB_data %>% 
  mutate(site = "Nursery") -> all_KB_data

all_KB_data$Temperature <- as.numeric(all_KB_data$Temperature)
```

plot all raw data 
```{r}
ggplot(all_KB_data, aes(x=Datetime_EST, y=Temperature, color = site)) +
  geom_point() +
  theme_bw() +
  scale_x_datetime(date_labels = "%b %Y",  # Customize the date format
                     date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


calculate daily thermal variability
```{r}
tidy_KB_data %>% 
  group_by(as.Date(Datetime_EST)) %>% 
  summarise(mean_daily_temp = mean(Temperature), sd_daily_temp = sd(Temperature), daily_range = (max(Temperature)-min(Temperature))) %>% 
  ggplot(., aes(x=`as.Date(Datetime_EST)`, y=daily_range)) +
  geom_line() +
  theme_bw() 
```

# join both datasets and plot temps 
```{r}
tidy_KB_data %>% 
  full_join(., CCC_temp_filtered) %>% 
  filter(as.Date(Datetime_EST) < "2021-12-01") %>% 
  ggplot(., aes(x=Datetime_EST, y=Temperature, color = site)) +
  geom_line() +
  theme_bw() +
  labs(x="Date", y = "Temp (ºC)") +
  scale_color_manual(values = c("CCC" = "orange", "Nursery" = "darkblue")) +
  scale_x_datetime(date_labels = "%b %Y",  # Customize the date format
                     date_breaks = "3 month") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_vline(xintercept=as.POSIXct(as.Date("2021-06-23")))
#ggsave("CCCvsnursery_temp.png", width=10, height = 7)
```

# save tidied dataset
```{r}
tidy_KB_data %>% 
  full_join(., CCC_temp_filtered) %>% 
  select(Temperature, Datetime_EST, site) %>% 
  as.data.frame() %>% 
  write_csv(., "tidy_KB_CCC_data.csv")
```


## virginia key buoy water temp data
```{r}
file_paths <- c("raw_data/virginiakeybuoy/vakf1h2020.txt", "raw_data/virginiakeybuoy/vakf1h2021.txt", "raw_data/virginiakeybuoy/vakf1h2022.txt")

process_file <- function(file_path) {
  data <- read.table(file_path, header = FALSE, sep = "", comment.char = "#", stringsAsFactors = FALSE)

# Read the first two lines to get the column names
lines <- read_lines(file_path, n_max = 2)

# Extract column names from the second line
column_names <- strsplit(lines[1], "\\s+")[[1]]

# Assign the column names to the data frame
colnames(data) <- column_names

data %>% 
  rename(Temperature = WTMP) %>% 
  select(`#YY`:mm,Temperature) -> data
  
data$Datetime <- ymd_hm(paste(data$`#YY`, data$MM, data$DD, data$hh, data$mm))

data$Datetime <- as.POSIXct(data$Datetime, tz="UTC")
data$Datetime_EST <- with_tz(data$Datetime, "America/New_York")

return(data)
}

# Initialize an empty list to store the processed data frames
all_data <- list()

# Loop over the file paths and process each file
for (file_path in file_paths) {
  data <- process_file(file_path)
  all_data[[file_path]] <- data
}

# Optionally, combine all data frames into one, if needed
combined_data <- do.call(rbind, all_data)

# View the combined data
print(combined_data)

combined_data %>% 
  select(Temperature, Datetime_EST) %>% 
  mutate(site = "VK_Buoy") -> vkbuoydata

rownames(vkbuoydata) <- NULL

#VK_Buoy data gets written as "999" if there is no available data for that time point, so filter that out

vkbuoydata %>% 
  filter(Temperature < 999) -> vkbuoydata

# Filter the data to select time points at 2-hour intervals
vkbuoydata <- vkbuoydata %>%
  filter(minute(Datetime_EST) == 0 & (hour(Datetime_EST) %% 2 == 0))
```

```{r}
tidy_KB_data <- read_csv("tidy_KB_CCC_data.csv")
```


```{r}
tidy_KB_data #every 2 hr

vkbuoydata %>% 
  select(Temperature, Datetime_EST) %>% 
  mutate(site = "VK Buoy") -> vkbuoydata_subset #every 2 hr

full_join(CCC_hobo, tidy_KB_data) %>% 
  full_join(., vkbuoydata_subset) %>% 
  select(!Date_GMT) %>% 
  filter(as.Date(Datetime_EST) < "2021-12-01" & as.Date(Datetime_EST) > "2021-06-20") %>% 
  ggplot(., aes(x=Datetime_EST, y=Temperature, color = site)) +
  geom_line() +
  theme_classic() +
  labs(x="Date") 
#ggsave("plot_withCCCHOBO.png")
```


